//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Table
    {
        public int ID_Marca { get; set; }
        public int ID_Modelo { get; set; }
        public int ID_Anno { get; set; }
        public int ID_Inyeccion { get; set; }
        public int ID_Bateria { get; set; }
        public int ID_Cilindrada { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Bateria Bateria { get; set; }
        public virtual Cilindrada Cilindrada { get; set; }
        public virtual Inyeccion Inyeccion { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
